apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: markdown-lint-pipeline
spec:
  params:
    - name: source-repo
      type: string
      description: Source code repository
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: "$(params.source-repo)
      taskRef:
        name: git-clone
        kind: "ClusterTask"
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: lint--repo
      runAfter:
        - clone-repository
      taskRef:
        name: markdown-lint
        kind: Task
      workspaces:
        - name: shared-workspace
          workspace: pipeline: shared-data
    params:
         - name: args
           value: ["."]	
  workspaces:
    - name: pipeline-shared-data
